name: In Progress Feature Workflow

on:
  push:
    branches:
    - feature/issue-*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write
  pull-requests: write

jobs:
  update-in-progress-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Extract Issue Number
        shell: bash
        run: echo "issue=$(echo ${GITHUB_REF#refs/heads/} | sed 's|[^0-9]||g')" >> $GITHUB_OUTPUT
        id: extract_issue
      - name: Output Issue Number
        run: echo "Issue Number- ${{ steps.extract_issue.outputs.issue }}"
      - name: Update Labels
        run: gh issue edit ${{ steps.extract_issue.outputs.issue }} --add-label "in progress" --remove-label "to do"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}